config/routes.rb
Rails.application.routes.draw do

  root 'mitts#index'

  get '/login', controller: :sessions, action: :new
  get '/signup', controller: :users, action: :new
  delete '/logout', controller: :sessions, action: :destroy
  get '/timeline', controller: :mitts, action: :index
  resources :mitts, except: [:edit, :update, :index]
  resources :users, except: [:index]
  resource :sessions, only: [:create]
end

app/models/mitt.rb
# == Schema Information
#
# Table name: mitts
#
#  id             :integer          not null, primary key
#  content        :text
#  user_id        :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  response_to_id :integer
#
# Indexes
#
#  index_mitts_on_response_to_id  (response_to_id)
#  index_mitts_on_user_id         (user_id)
#

class Mitt < ActiveRecord::Base
  belongs_to :user, inverse_of: :mitts
  has_many :responses, class_name: "Mitt", foreign_key: 'response_to_id'
  belongs_to :response_to, class_name: "Mitt"

  validates :content, length: { in: 1..140 }
  validates :user, presence: true

  def username
    return user.username unless user == nil
    return ''
  end

  def by_user?(test_user)
    user == test_user
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string
#  password_digest :string
#  email           :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_secure_password

  validates :username, uniqueness: true, presence: true
  validates :email, uniqueness: true, presence: true

  has_many :mitts, inverse_of: :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
    def current_user
      User.where(id: session[:user_id]).first
    end

    def logged_in?
      return current_user != nil
    end

    helper_method :current_user
    helper_method :logged_in?
end

app/controllers/mitts_controller.rb
class MittsController < ApplicationController
  before_action :set_mitt, only: [:show, :edit, :update, :destroy]

  # GET /mitts
  # GET /mitts.json
  def index
    @mitts = Mitt.all.order(created_at: :desc)
  end

  # GET /mitts/1
  # GET /mitts/1.json
  def show
  end

  # GET /mitts/new
  def new
    @mitt = Mitt.new
  end

  # POST /mitts
  def create
    @mitt = Mitt.new(mitt_params)
    @mitt.user = current_user
    if @mitt.save
      redirect_to timeline_url
    else
      render :new
    end
  end

  # DELETE /mitts/1
  def destroy
    @mitt.destroy
    flash[:success] = 'Mitt was successfully destroyed.'
    redirect_to timeline_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mitt
      @mitt = Mitt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mitt_params
      params.require(:mitt).permit(:content, :response_to_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_username(session_params[:username])
    if user && user.authenticate(session_params[:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome"
      redirect_to root_url
    else
      flash.now[:danger] = "Username or password don't match"
      render :new
    end
  end

  def new
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

  private

    def session_params
      params.require(:session).permit(:username, :password)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  # GET /static_pages
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users/1
  def show

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:success] = 'User was successfully created.'
      redirect_to root_url
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      flash[:success] = 'User was successfully updated.'
      redirect_to @user
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    flash[:success] = 'User was successfully destroyed.'
    redirect_to users_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mitts_helper.rb
module MittsHelper
  def link_usernames(text)
    text.gsub /@(\w+)/ do |username|
      user = User.where(username: username.gsub('@', '')).first
      if user != nil
        link_to(username, user_path(user))
      else
        username
      end
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Mitter</title>
        <%= stylesheet_link_tag    'application', media: 'all' %>
        <%= javascript_include_tag 'application' %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-xs-4 text-left">
                    <%= link_to 'Home', root_url %>
                </div>
                <% if logged_in? %>
                <div class="col-xs-4 text-center">
                    <%= link_to 'My Profile', user_url(current_user) %>
                </div>
                <div class="col-xs-4 text-right">
                    <%= link_to 'Logout', logout_url, method: :delete %>
                </div>
            <% else %>
                <div class="col-xs-4 text-center">
                    <%= link_to 'Signup', signup_url %>
                </div>
                <div class="col-xs-4 text-right">
                    <%= link_to 'Login', login_url %>
                </div>
                <% end %>
            </div>
        </div>
        <div class="container">
            <% flash.each do |name, msg| -%>
            <%= content_tag :div, {class: ["alert", "alert-#{name}"], role: 'alert'} do %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <%= msg %>
            <% end -%>
            <% end -%>
        </div>

        <div class="container">
            <%= yield %>
        </div>

    </body>
</html>

app/views/mitts/_form.html.erb
<%= form_for(mitt) do |f| %>
  <%= f.hidden_field :response_to_id %>
  <div class="form-group">
    <%= f.label :content, "New mitt:" %><br>
    <div class="input-group">
      <%= f.text_area :content, class: 'form-control' %>
      <span class="input-group-addon count">0</span>
    </div>
  </div>
  <%= f.submit class:"btn btn-primary pull-right"%>
  <div class="clearfix"></div>
  <% if mitt.errors.any? %>
  <ul>
    <% mitt.errors.full_messages.each do |message| %>
      <li class="text-danger"><%= message %></li>
    <% end %>
  </ul>
  <% end %>
<% end %>

app/views/mitts/_mitt.html.erb
<div class="mitt">
    <div class="mitt-header">
        <%= link_to mitt.username, mitt.user %>
        wrote
        <%= link_to time_ago_in_words(mitt.created_at), mitt %>
        ago:
    </div>
    <div class="mitt-content">
        <%= sanitize link_usernames(mitt.content) %>
    </div>
    <div class="mitt-footer">
    <% if mitt.by_user? current_user %>
      <%= link_to 'Delete', mitt, method: :delete, class: 'btn btn-danger btn-xs' %>
    <% end %>
    </div>
</div>

app/views/mitts/index.html.erb
<h1>Mitts</h1>

<% if logged_in? %>
<div class="row">
  <div class="col-xs-12 col-md-8 col-md-offset-2">
    <%= render partial: 'form', locals: {mitt: Mitt.new} %>
  </div>
</div>
<% end %>

<div class="row">
  <div class="col-xs-12 col-md-8 col-md-offset-2">
    <% @mitts.each do |mitt| %>
      <%= render partial: 'mitt', object: mitt %>
    <% end %>
  </div>
</div>

app/views/mitts/new.html.erb
<h1>New Mitt</h1>

<%= render partial:'form', locals: {mitt: @mitt} %>

<%= link_to 'All mitts', timeline_path %>

app/views/mitts/show.html.erb
<% unless @mitt.response_to.nil? %>
<div class="row">
  <div class="col-xs-12 col-md-8 col-md-offset-2">
    <h2>Original:</h2>
    <%= render partial:'mitt', object: @mitt.response_to %>
  </div>
</div>
<% end %>

<div class="row">
  <div class="col-xs-12 col-md-8 col-md-offset-2">
    <h2>Mitt:</h2>
    <%= render @mitt %>
  </div>
</div>

<% if @mitt.responses.any? %>
<div class="row">
  <div class="col-xs-12 col-md-8 col-md-offset-2">
    <h2>Responses:</h2>
    <% @mitt.responses.each do |mitt| %>
      <%= render partial:'mitt', object: mitt %>
    <% end %>
  </div>
</div>
<% end %>

<% if logged_in? %>
<div class="row">
  <div class="col-xs-12 col-md-8 col-md-offset-2">
    Respond to this mitt:
    <%= render partial:'form', locals:{mitt: Mitt.new(response_to: @mitt)} %>
  </div>
</div>
<% end %>

<div class="row">
  <div class="col-xs-12 col-md-8 col-md-offset-2">
    <%= link_to 'All mitts', timeline_path %>
  </div>
</div>

app/views/static_pages/index.html.erb
<h1>Welcome to the Exam</h1>
<div class="row">
  <div class="col-xs-12 col-md-8 col-md-offset-2">
    <p>
      This is the welcome page. It should be replaced with something else, such
      as a <%= link_to 'list of current mitts', timeline_path %>
    </p>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <div class="form-group <%= @user.errors.include?(:username) ? 'has-error' : '' %>">
    <%= f.label :username, class: 'control-label' %>
    <%= f.text_field :username, class: 'form-control' %>
    <% if @user.errors.include?(:username) %>
    <% @user.errors.full_messages_for(:username).each do |message| %>
      <span class="help-block"><%= message %></span>
    <% end %>
    <% end %>
  </div>
  <div class="form-group <%= @user.errors.include?(:email) ? 'has-error' : '' %>">
    <%= f.label :email, class: 'control-label' %>
    <%= f.text_field :email, class: 'form-control' %>
    <% if @user.errors.include?(:email) %>
    <% @user.errors.full_messages_for(:email).each do |message| %>
      <span class="help-block"><%= message %></span>
    <% end %>
    <% end %>

  </div>
  <div class="form-group <%= @user.errors.include?(:password) ? 'has-error' : '' %>">
    <%= f.label :password, class: 'control-label' %>
    <%= f.password_field :password, class: 'form-control' %>
    <% if @user.errors.include?(:password) %>
    <% @user.errors.full_messages_for(:password).each do |message| %>
      <span class="help-block"><%= message %></span>
    <% end %>
    <% end %>
  </div>
  <div class="form-group <%= @user.errors.include?(:password_confirmation) ? 'has-error' : '' %>">
    <%= f.label :password_confirmation, class: 'control-label' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
    <% if @user.errors.include?(:password_confirmation) %>
    <% @user.errors.full_messages_for(:password_confirmation).each do |message| %>
      <span class="help-block"><%= message %></span>
    <% end %>
    <% end %>
  </div>

  <%= f.submit class:"btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit user <%= @user.username %></h1>

<div class="row">
  <div class="col-xs-12 col-md-8 col-md-offset-2">
    <%= render 'form' %>
    <%= link_to 'Cancel edits', @user %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-xs-12 col-md-6 col-md-offset-3">
    <p>
        Create your account here
    </p>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

<div class="row">
  <div class="col-xs-12 col-md-6 col-md-offset-3">
    Do you have an account already? <%= link_to 'Login', login_path %>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.username -%>'s mitts:</h1>

<% if current_user == @user %>
<div class="row">
  <div class="col-xs-12 col-md-8 col-md-offset-2">
    <%= render partial: 'mitts/form', locals: {mitt: Mitt.new} %>
  </div>
</div>
<% end %>


<div class="row">
  <div class="col-xs-12 col-md-8 col-md-offset-2">
    <% @user.mitts.order(created_at: :desc).each do |mitt| %>
      <%= render partial:'mitts/mitt', object: mitt %>
    <% end %>
  </div>
</div>

<% if current_user == @user %>
<div class="row">
  <div class="col-xs-12 col-md-8 col-md-offset-2">
    <%= link_to 'Edit user', edit_user_path %>
  </div>
</div>
<% end %>